### ISSUE TITLE
sys-libs/libnvidia-container-1.14.6 failed to be build in some profile 

### ISSUE THREAD

**Issue by weipeng1999** [vowstar/vowstar-overlay#19]
due to the upstream add -fplan9-extension in $CFLAGS at Makefile, this package can only be build by gcc. can we just add CC=gcc in ebuild?

**Comment by vowstar** [comment]
I tried committing a correction to upstream.

The cause of this bug was introduced by https://github.com/NVIDIA/libnvidia-container/commit/162507e7876b68c43f15248a3792a1e0ee9d6f91, but https://reviews.llvm.org/D3853 still has no result. A better strategy is to replace with `-fms-extensions`.

You can try the latest commits.

**Comment by weipeng1999** [comment]
> I tried committing a correction to upstream.
> 
> The cause of this bug was introduced by [NVIDIA/libnvidia-container@162507e](https://github.com/NVIDIA/libnvidia-container/commit/162507e7876b68c43f15248a3792a1e0ee9d6f91), but https://reviews.llvm.org/D3853 still has no result. A better strategy is to replace with `-fms-extensions`.
> 
> You can try the latest commits.

it works, thanks :)
